# Autogenerated file
onerror {
	quit -f -code 1
}
vmap -c
if [file exists sim_build/work] {vdel -lib sim_build/work -all}
vlib sim_build/work
vmap work sim_build/work
vlog -work work +define+COCOTB_SIM -sv -timescale 1ns/1ps -mfcu +acc  threshold.v
vsim  -onfinish exit -pli /u/kanipogu/.local/lib/python3.6/site-packages/cocotb/libs/libcocotbvpi_modelsim.so   work.threshold
onbreak resume
run -all
quit
